refresh_rate = "30 seconds"

[appenders.stdout]
kind = "console"

[appenders.requests]
kind = "file"
path = "log/requests.log"

[rolling_appender]
kind = "rolling_file"
path = "log/foo.log"
append = true

  [rolling_appender.encoder]
  kind = "pattern"
  pattern = "{d} - {m}{n}"

  [rolling_appender.policy]
  kind = "compound"

    [rolling_appender.policy.trigger]
    kind = "size"
    limit = "10 mb"

    [rolling_appender.policy.roller]
    kind = "delete"

[root]
level = "warn"
appenders = [ "stdout" ]

[loggers."app::backend::db"]
level = "info"

[loggers."app::requests"]
level = "info"
appenders = [ "requests" ]
additive = false
