refresh_rate = "30 seconds"

[appenders.console]
kind = "console"

[appenders.file]
kind = "file"
path = "log/output.log"
encoder.pattern = "{d} - {l} - {m}{n}"

[root]
level = "error"
appenders = ["console", "file"]

[loggers.my_crate]
level = "error"
appenders = ["console", "file"]
additive = false
